/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\brain1.glb -o src\components\Brain1GLB.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    brain_cerebellum_0: THREE.Mesh
    brain_Frontal_0: THREE.Mesh
    brain_lambert1_0: THREE.Mesh
    brain_Occipital_0: THREE.Mesh
    brain_Parietal_0: THREE.Mesh
    brain_Temporal_0: THREE.Mesh
    Cube: THREE.Mesh
  }
  materials: {
    cerebellum: THREE.MeshStandardMaterial
    Frontal: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    Occipital: THREE.MeshStandardMaterial
    Parietal: THREE.MeshStandardMaterial
    Temporal: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/brain1.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="4ede1ed98e6e45fdab771ace5d13471dfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="brain" position={[0.391, 0, 0.778]}>
                  <mesh name="brain_cerebellum_0" geometry={nodes.brain_cerebellum_0.geometry} material={materials.cerebellum} />
                  <mesh name="brain_Frontal_0" geometry={nodes.brain_Frontal_0.geometry} material={materials.Frontal} />
                  <mesh name="brain_lambert1_0" geometry={nodes.brain_lambert1_0.geometry} material={materials.lambert1} />
                  <mesh name="brain_Occipital_0" geometry={nodes.brain_Occipital_0.geometry} material={materials.Occipital} />
                  <mesh name="brain_Parietal_0" geometry={nodes.brain_Parietal_0.geometry} material={materials.Parietal} />
                  <mesh name="brain_Temporal_0" geometry={nodes.brain_Temporal_0.geometry} material={materials.Temporal} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/brain1.glb')
